language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
  - "pypy3"
install:
  - sudo apt-get install -y zip p7zip-full
  - pip install --upgrade . pytest pytest-cov codecov
script: pytest -vv --cov=stripzip .
after_success: codecov

jobs:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "pypy"
