language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install .
script:
  - python -m zipfile -c test.zip setup.py
  - stripzip test.zip
